services:
  devel:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: ${HOST_UID}
        GID: ${HOST_GID}
        USER_NAME: developer
    volumes:
      - ..:/workspace
      - ${HOST_HOME}/.ssh:/home/developer/.ssh:ro
    working_dir: /workspace
    tty: true
    networks:
      - devnet

networks:
  devnet:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: ${HOST_MTU}